heat_template_version: 2021-04-16

description: >
  Plantilla para la creación de una infra de red para un proyecto.
  Red, 2 subnets, router

parameters:

  # Nombre de la red (red-del-proyecto) y de las subnets (subnet-privada, subnet-expuesta) y del router (el-router-del-proyecto)
  # Rangos en las subnets 10.0.0.0/24 y 20.0.0.0/24
  # dhcp SI




  nombre_del_usuario_monitorizacion:
    type:             string
    description:      Nombre del usuario de monitorizacion del proyecto.
    default:          monitorizacion

resources:

    el_dominio:               
        type:                 OS::Keystone::Domain
        properties:
          description:        Nuevo dominio para mi cliente
          name:               
            get_param:        nombre_del_dominio

outputs:

  # Los IDs de los recursos que se creen
  # ID de la network, de las subnets, del router 

  password_del_usuario_manager:
    description: Password aleatorio generado para el usuario manager.
    value: 
      get_attr:
        - password_aleatorio_manager
        - value
