heat_template_version: 2021-04-16

description: >
  Plantilla para la creación de dos máquinas virtuales, 
  una con NGINX y otra con MariaDB.
  Con sus respectivos puertos abiertos y una ip flotante para la máquina de NGINX.

parameters:

  maquina1:
    type:                 json
    description:          Datos de la máquina 1 (NGINX)

  maquina2:
    type:                 json
    description:          Datos de la máquina 2 (MariaDB)

  claveSSH:
    type:                 string
    description:          Nombre del par de claves a usar para acceder a las máquinas

  imagen_so:
    type:                 json
    description:          Datos de la imagen a usar para las máquinas

  red:
    type:                 json
    description:          Datos de la red a usar para las máquinas

  redExterna:
    type:                 json
    description:          Datos de la red externa a usar para las máquinas

resources:

  la_imagen_so:
      type:                             OS::Glance::WebImage
      properties:
        name: 
          get_param:
                                      - imagen_so
                                      - nombre

        active:                         true
        container_format:               bare
        disk_format:                    qcow2
        visibility: 
          get_param:
                                      - imagen_so
                                      - visibilidad
        location: 
          get_param:
                                      - imagen_so
                                      - url

        extra_properties:
          os_distro:                    cirros
          os_version:                   0.6.2
          uso:                          labs

  security_group_maquina1:
      type:                         OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
              template:             sg-NOMBRE
              params:
                 NOMBRE:
                    get_param:
                                  - maquina1
                                  - nombre
        description: >  
                                    Security group para la máquina 1 (que llevará NGINX).
                                    Abre los puertos http, https, ssh y ICMP.
        rules: 
          - direction:              ingress
            ethertype:              IPv4
            port_range_min:         80
            port_range_max:         80
            protocol:               tcp
            remote_ip_prefix:       0.0.0.0/0

          - direction:              ingress
            ethertype:              IPv4
            port_range_min:         443
            port_range_max:         443
            protocol:               tcp
            remote_ip_prefix:       0.0.0.0/0

          - direction:              ingress
            ethertype:              IPv4
            port_range_min:         22
            port_range_max:         22
            protocol:               tcp
            remote_ip_prefix:       0.0.0.0/0

          - direction:              ingress
            ethertype:              IPv4
            protocol:               icmp
            remote_ip_prefix:       0.0.0.0/0

  security_group_maquina2:
      type:                         OS::Neutron::SecurityGroup
      properties:
        name:
          str_replace:
              template:             sg-NOMBRE
              params:
                 NOMBRE:
                    get_param:
                                  - maquina2
                                  - nombre
        description: >  
                                    Security group para la máquina 2 (que llevará MariaDB).
                                    Abre los puertos ICMP y SSH y MARIADB (3306).
                                    Solo se debe permitir tráfico desde el las ips en la red expuesta
        rules: 
          - direction:              ingress
            ethertype:              IPv4
            port_range_min:         3306
            port_range_max:         3306
            protocol:               tcp
            remote_ip_prefix:
              get_param:
                                  - red
                                  - subnetExpuesta
                                  - cidr

          - direction:              ingress
            ethertype:              IPv4
            port_range_min:         22
            port_range_max:         22
            protocol:               tcp
            remote_ip_prefix:       0.0.0.0/0
          - direction:              ingress
            ethertype:              IPv4
            protocol:               icmp
            remote_ip_prefix:
              get_param:
                                  - red
                                  - subnetExpuesta
                                  - cidr

  ip_flotante_maquina1:
    type:                           OS::Neutron::FloatingIP
    properties:
      floating_network:
        get_param:
                                  - redExterna
                                  - nombre

  asociacion_ip_flotante_maquina1: # Con esto lo que configuro es el NAT
    type:                         OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: 
        get_resource:             ip_flotante_maquina1
      port_id: 
        get_resource:             puerto_maquina1

# Volumen para la BBDD 5Gbs
# Necesitamos crear el volumen:   OS::Cinder::Volume              tamaño
# Y luego asociarlo a la máquina: OS::Cinder::VolumeAttachment    id del volumen y el id de la máquina
  volumen_maquina2:
    type:                 OS::Cinder::Volume
    properties:
      name:
        str_replace:
            template:             volumen-NOMBRE
            params:
               NOMBRE:
                  get_param:
                                    - maquina2
                                    - nombre
      size: 
        get_param:
                                  - maquina2
                                  - volumen

  asociacion_volumen_maquina2:
    type:                 OS::Cinder::VolumeAttachment
    properties:
      volume_id:
        get_resource:         volumen_maquina2
      instance_uuid:
        get_resource:         la_maquina2

  puerto_maquina1:
    type:                           OS::Neutron::Port
    properties:
      name:
          str_replace:
              template:             puerto-NOMBRE
              params:
                 NOMBRE:
                    get_param:
                                  - maquina1
                                  - nombre 
      network_id:
        get_param:
                                  - red
                                  - id
      fixed_ips:
        - subnet:
            get_param:
                                  - red
                                  - subnetExpuesta
                                  - id
      security_groups:
        - get_resource:             security_group_maquina1  

  puerto_maquina2:
    type:                           OS::Neutron::Port
    properties:
      name:
          str_replace:
              template:             puerto-NOMBRE
              params:
                 NOMBRE:
                    get_param:
                                  - maquina2
                                  - nombre 
      network_id:
        get_param:
                                  - red
                                  - id
      security_groups:
        - get_resource:             security_group_maquina2
      fixed_ips:
        - subnet:
            get_param:
                                  - red
                                  - subnetPrivada
                                  - id
          ip_address:
            get_param:
                                  - maquina2
                                  - ip_fija

  la_maquina1:
    type:                           OS::Nova::Server
    properties:
      name:
        get_param:
                                  - maquina1
                                  - nombre
      image:
        get_resource:               la_imagen_so
      flavor: 
        get_param:
                                  - maquina1
                                  - flavor
      networks:
        - port: 
            get_resource:         puerto_maquina1
      key_name:
        get_param:                claveSSH

  la_maquina2:
    type:                           OS::Nova::Server
    properties:
      name:
        get_param:
                                  - maquina2
                                  - nombre
      image:
        get_resource:               la_imagen_so
      flavor: 
        get_param:
                                  - maquina2
                                  - flavor
      networks:
        - port: 
            get_resource:         puerto_maquina2
      key_name:
        get_param:                claveSSH

outputs:

  id_maquina1:
    description:                Id de la máquina 1 (NGINX)
    value:
      get_resource:             la_maquina1
  
  id_maquina2:
    description:                Id de la máquina 2 (MariaDB)
    value:
      get_resource:             la_maquina2

